config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:index, :show, :new, :create] do
    resources :answers, only: :create
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "welcome#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :body, presence: true

  def self.recent
    order(created_at: :desc).first
  end

  def digest
    body.lines[0..4].join("\r\n")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/custom_render.rb
class CustomRender < Redcarpet::Render::HTML
  def image(image_link, title, content)
    %(<image src="#{image_link}" class="img-fluid" alt="#{content}" title="#{title}"/>)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: false

  validates :body, presence: true

  def self.recent
    order(created_at: :desc).first
  end

  def digest
    body.lines[0..4].join("\r\n")
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :questions, dependent: false
  has_many :answers,   dependent: false

  def self.from_omniauth(access_token)
    data = access_token.info
    user = where(email: data['email']).first

    unless user
        user = create(name: data['name'],
                      email: data['email'],
                      password: Devise.friendly_token[0,20])
    end
    user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question

  def create
    @answer = @question.answers.new(answer_params.merge(user: current_user))
    if @answer.save
      redirect_to question_path(@answer.question)
    else
      head :bad_request
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = current_user.questions
  end

  def new
    @question = current_user.questions.build
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = current_user.questions.create(question_params)
    if @question
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        @user = User.from_omniauth(request.env['omniauth.auth'])
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @random_quote = Question.order("RANDOM()").first
    @recent_sample = [Question, Answer].map(&:recent).compact
  end
end

app/helpers/application_helper.rb
require 'redcarpet'
require 'custom_render'

module ApplicationHelper
  def question_owner(question)
    question.user == current_user ? "You" : question.user&.name || "Deleted user"
  end

  def markdown(body)
    renderer = CustomRender.new(filter_html: true, hard_wrap: true)
    @markdown = Redcarpet::Markdown.new( renderer, autolink: true, tables: true)
    @markdown.render(body).html_safe
  end
end

app/views/answers/_answer.html.erb
<div class="col-md-6">
  <div class="card flex-md-row mb-4 box-shadow">
    <div class="card-body d-flex flex-column align-items-start">
      <strong class="d-inline-block mb-2 text-success">Answer</strong>
      <p class="card-text mb-auto"><%= markdown(answer.digest) %></p>
      <div class="mb-1 text-muted"><%= answer.created_at %></div>
      <div class="mb-1 text-muted"><%= question_owner(answer) %></div>
      <%= link_to "Show more", answer.question %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120151211-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-120151211-1');
    </script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cookpad Q&amp;A</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="container">
      <header class="qanda-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <%= link_to "Ask a question", new_question_path, class: "text-muted" %>
          </div>
          <div class="col-md-auto text-center">
            <%= link_to "Cookpad Q&A", root_path, class: "qanda-header-logo text-dark"%>
          </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
              <div class="row">
              <% if user_signed_in? %>
                <div class="col d-flex justify-content-end align-items-end">
                  <%= link_to current_user.name, questions_path, class: "btn btn-sm btn-outline-secondary" %>
                </div>
                <div class="col d-flex justify-content-end align-items-center">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %>
                </div>
              <% else %>
                <div class="col d-flex justify-content-end align-items-center">
                <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, class: "btn btn-sm btn-outline-secondary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </header>

      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>

    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="col-md-6">
  <div class="card flex-md-row mb-4 box-shadow">
    <div class="card-body d-flex flex-column align-items-start">
      <strong class="d-inline-block mb-2 text-primary">Question</strong>
      <p class="card-text mb-auto"><%= markdown(question.digest) %></p>
      <div class="mb-1 text-muted"><%= question_owner(question) %></div>
      <div class="mb-1 text-muted"><%= question.created_at %></div>
      <%= link_to "Show more", question %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<h1 class="display-4 font-italic">Your Questions</h1>

<% if @questions %>
<div class="row mb-2">
  <% @questions.each do |question| %>
  <%= render question %>
  <% end %>
</div>
<% else %>
You don't have any questions yey. Why not <%= link_to "create one", new_question_path %>?
<% end %>

app/views/questions/new.html.erb
<%= form_for(@question) do |f| %>
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">Your question</h1>
      <div contenteditable></div>
      <p class="lead my-3"><%= f.text_area :body, cols: 30, rows: 5, placeholder: "You can use markdown here...", class: "text-white rounded bg-dark" %></p>
      <%= f.submit class: "btn btn-light" %>
    </div>
  </div>
<% end %>

app/views/questions/show.html.erb
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        Question from <%= question_owner(@question) %>
      </h3>

      <div class="blog-post">
        <!-- <h2 class="blog-post-title">Sample blog post</h2> -->
        <p class="blog-post-meta"><%= @question.created_at %> by <%= question_owner(@question) %></p>
        <%= markdown @question.body %>
      </div><!-- /.blog-post -->
    </div><!-- /.blog-main -->
  </div><!-- /.row -->

  <% @question.answers.each do |answer| %>
    <div class="row">
      <div class="col-md-8 blog-main">
        <h3 class="pb-3 mb-4 font-italic border-bottom">
          Answer from <%= question_owner(answer) %>
        </h3>

        <div class="blog-post">
          <!-- <h2 class="blog-post-title">Sample blog post</h2> -->
          <p class="blog-post-meta"><%= answer.created_at %> by <%= question_owner(answer) %></p>
          <%= markdown answer.body %>
        </div><!-- /.blog-post -->
      </div><!-- /.blog-main -->
    </div><!-- /.row -->
  <% end %>
</main><!-- /.container -->

<%= form_for [@question, Answer.new] do |f| %>
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">Your answer</h1>
      <p class="lead my-3">
        <%= f.text_area :body, cols: 30, placeholder: "", class: "text-white rounded bg-dark" %>
      </p>
      <%= f.submit class: "btn btn-light" %>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<% if @random_quote %>
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <p class="lead my-3"><%= markdown(@random_quote.digest) %></p>
      <p class="lead mb-0"><%= link_to "Show more", @random_quote, class: "text-white font-weight-bold" %></p>
    </div>
  </div>
<% end %>

<div class="row mb-2">
  <%= render @recent_sample %>
</div>